### ISSUE TITLE
Cannot find discoIPC module on linux

### ISSUE THREAD

**Issue by drxjason** [An0n3m0us/DiscordRPBlender#2]
Hello, when i run` blender -P discordrpblender.py` on my "linux terminal" I get this line 
```
File "/home/jason/discordrpblender.py", line 4, in <module>
    from discoIPC import ipc
ModuleNotFoundError: No module named 'discoIPC'
```
But i have discoIPC installed using pip

**Comment by An0n3m0us** [comment]
What version of Blender are you using?

Also, did you use `pip3` to install discoIPC? I think you used `pip` for Python 2.
You need to install `discoIPC` for Python 3 (I'm using Python 3.5)

**Comment by An0n3m0us** [comment]
Closed until further discussion is required
