### ISSUE TITLE
Causes lag inside of Blender

### ISSUE THREAD

**Issue by kilbouri** [An0n3m0us/DiscordRPBlender#3]
Since installing DRPB there has been a significant amount of lag while working inside of Blender.

Possibly useful/relevant information:
- Using the Steam version of Blender with launchoptions `-P "PATHTODRPB.py"`
- i5 8600K/GTX 1660/16GB RAM
- No system resources are over 25% during use [EDIT]

**Comment by An0n3m0us** [comment]
I suppose it is input lag? My system specs are much lower than that and I haven't ever seen any signs of lag or high RAM usage.

Does it occur while you are using Blender without DiscordRPBlender?
Does it occur while you're using Blender natively (without Steam)?
Also, are you using Linux (if so, which distro & version) or Windows (if so, which version)?

I'll test a few things out and see if I can reproduce this issue.

Thanks for reporting this!

**Comment by kilbouri** [comment]
It only appears to happen within the steam version. I'll try a few things on my end, it might be easily resolved. I'm running Windows 10 (latest update, whatever that may be)

**Comment by kilbouri** [comment]
Yea, I'm really not sure what causes it.

It does seem like input lag. It happens **only** when started with a Steam launch option in Blender. Running it with the `blender` command directly doesn't cause any lag. To be as precise as possible, I am using Blender v2.83.5.

**Comment by An0n3m0us** [comment]
Then this is a Steam issue. I cannot see how this could be an issue with DiscordRPBlender when it works fine when using Blender natively.

**Comment by kilbouri** [comment]
Alright.
